---
:sshPrivateKeyPath: ~/.ssh/id_rsa
:digitalOceanToken: TOKENGOESHERE
:intnetName: neverwinterDP
machines:
- name: queuengin
  ram: 512MB
- name: sparkngin
  ram: 512MB
- name: demandspike
  ram: 512MB
